### ISSUE TITLE
1.5 a12s inception + debuff

### ISSUE THREAD

**Issue by applepudding** [applepudding/ffxiv.act.applbot#1]
Wrong position for shared debuff on inception+debuff phase.
Fixing... and uploading in few hrs!

**Comment by IrealiTY** [comment]
Any way to give the a12 positions a test run before an actual a12 attempt?

**Comment by applepudding** [comment]
Yea, uhm, ill upload my "simulator" to test stuff, in 1 hr ish.

**Comment by applepudding** [comment]
https://github.com/applepudding/ffxiv.act.logsim

I hope it works n useful, sorry that it's still a bit complicated to use :(
