### ISSUE TITLE
Missing encounters from dropdown

### ISSUE THREAD

**Issue by rumlefisk** [applepudding/ffxiv.act.applbot#2]
This may be intentional, but none of the Stormblood encounters are on the encounter dropdown list, although it still does callouts properly. Nothing will show up on the mini overlay if its not selected here.

![advanced combat tracker_2017-08-24_18-59-45](https://user-images.githubusercontent.com/22837521/29678383-a3face36-88fe-11e7-879e-ff3f1c8709db.png)

**Comment by IrealiTY** [comment]
Check if the xml files are in `ACT_INSTALL_FOLDER/applebot/`

**Comment by rumlefisk** [comment]
They are, its a fresh install

![image](https://user-images.githubusercontent.com/22837521/29720142-39e217a0-89b9-11e7-8f3f-91a9820738d0.png)

**Comment by rumlefisk** [comment]
Showed up almost 2 weeks ago, forgot to close it
