### ISSUE TITLE
after new FFXIV ACT plugin its not working?

### ISSUE THREAD

**Issue by Zentence** [applepudding/ffxiv.act.applbot#3]
seems now they updated the FFXIV_ACT_Plugin finally with the zones and such it seems to not call out anything for Neo Exdeath atleast? i dunno if it could be the reason or not?

**Comment by rumlefisk** [comment]
Still an issue. After the update (FFXIV_ACT_Plugin), it'll read from the scripts, but not from the encounter triggers. Running the FFXIV_ACT_Plugin 1.5.1.5 its the other way around. Wont read scripts, but the triggers work.

**Comment by applepudding** [comment]
o_O sorry, i havent checked in awhile.
So, everytime main ffxiv plugin is updated, i have to update mine too. And i did.. it should work now. I'll put the latest build on release page. Mmmm.. if still not working, pls check if act is allowed thru firewall, ran as admin, and the encounter reset timer is set to around 50s.
