### ISSUE TITLE
Possible to edit xmls from within ACT?

### ISSUE THREAD

**Issue by Zentence** [applepudding/ffxiv.act.applbot#4]
just wondering if it would be possible to do something so you can change the xml file within ACT at the plugins "main" window where it says "phase #, details, Timing, Speak, Trigger" if i wanted to add extra speak out? :) instead of having to go into the actual XML file and edit it.

**Comment by applepudding** [comment]
ooh ill add this feature soon :D thankies

**Comment by Zentence** [comment]
nice awesome job on the plugin btw :D and fast updating after the patch xD with Shinryu :D was surprised :D
